---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: twitter-sentiment-analysis
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: v1
    kind: ReplicationController
    name: twitter-sentiment-analysis
  targetCPUUtilizationPercentage: 70