---
kind: ReplicationController
apiVersion: v1
metadata:
  name: twitter-sentiment-analysis
  labels:
    app: sentiment-analysis
    role: app
spec:
  replicas: 1
  selector:
    app: sentiment-analysis
    role: app
  template:
    metadata:
      labels:
        app: sentiment-analysis
        role: app
    spec:
      containers:
      - name: twitter-sentiment-analysis
        image: docker.pkg.github.com/pmanickavelu/twitter-sentiment-analysis/simple_lstm:1
        imagePullPolicy: Always
        env:
        - name: USER
          value: False
        resources:
          limits:
            cpu: 2000m
          requests:
            cpu: 1000m
        ports:
        - name: http-server
          containerPort: 5000
